- name: kubernetes-hardening-master
  hosts: kubernetes_masters
  become: yes
  roles:
    - { role: kubernetes-hardening-master, tags: ["kubernetes-hardening-master"] }

- name: kubernetes-hardening-node
  hosts: kubernetes_nodes
  become: yes
  roles:
    - { role: kubernetes-hardening-node, tags: ["kubernetes-hardening-node"] }

- name: kube-proxy
  hosts: kubernetes_master
  become: yes
  roles:
    - { role: kube-proxy, tags: ["kube-proxy"] }

- name: kube-apiserver
  hosts: kubernetes_masters
  become: yes
  roles:
    - { role: kube-apiserver, tags: ["kube-apiserver"] }