---
- stat: path=/lib/systemd/system/docker.service
  register: res

- name: |
        "3.1 Ensure that docker.service file ownership is set to root:root (Scored)"
        "3.2 Ensure that docker.service file permissions are set to 644 or more restrictive (Scored)"
  file:
    path: /lib/systemd/system/docker.service
    owner: root
    group: root
    mode: 0644
    state: file
  when: res.stat.exists == True
  tags:
   - scored
   - section3.1
   - section3.2

- stat: path=/usr/lib/systemd/system/docker.socket
  register: res

- name: |
        "3.3 Ensure that docker.socket file ownership is set to root:root (Scored)"
        "3.4 Ensure that docker.socket file permissions are set to 644 or more restrictive (Scored)"
  file:
    path: /usr/lib/systemd/system/docker.socket
    owner: root
    group: root
    mode: 0644
    state: file
  when: res.stat.exists == True
  tags:
   - scored
   - section3.3
   - section3.4


- stat: path=/etc/docker
  register: res

- name: |
        "3.5 Ensure that /etc/docker directory ownership is set to root:root (Scored)"
        "3.6 Ensure that /etc/docker directory permissions are set to 755 or more restrictive (Scored)"
  file:
    path: /etc/docker
    owner: root
    group: root
    mode: 0755
    state: directory
  when: res.stat.exists == True
  tags:
   - scored
   - section3.5
   - section3.6


# - name: |
#         "3.7 Ensure that registry certificate file ownership is set to root:root (Scored)"
#         "3.8 Ensure that registry certificate file permissions are set to 444 or more restrictive (Scored)"

- stat: path="{{ server_cert_path }}/{{ ca_cert }}"
  register: res

- name: |
        "3.9 Ensure that TLS CA certificate file ownership is set to root:root (Scored)"
        "3.10 Ensure that TLS CA certificate file permissions are set to 444 or more restrictive (Scored)"
  file:
    path: "{{ server_cert_path }}/{{ ca_cert }}"
    owner: root
    group: root
    mode: 0444
    state: file
  when: res.stat.exists == True
  tags:
   - scored
   - section3.9
   - section3.10


- stat: path="{{ server_cert_path }}/{{ server_cert }}"
  register: res

- name: |
        "3.11 Ensure that Docker server certificate file ownership is set to root:root (Scored)"
        "3.12 Ensure that Docker server certificate file permissions are set to 444 or more restrictive (Scored)"
  file:
    path: "{{ server_cert_path }}/{{ server_cert }}"
    owner: root
    group: root
    mode: 0444
    state: file
  when: res.stat.exists == True
  tags:
   - scored
   - section3.11
   - section3.12


- stat: path="{{ server_cert_path }}/{{ server_cert_key }}"
  register: res

- name: |
        "3.13 Ensure that Docker server certificate key file ownership is set to root:root (Scored)"
        "3.14 Ensure that Docker server certificate key file permissions are set to 400 (Scored)"
  file:
    path: "{{ server_cert_path }}/{{ server_cert_key }}"
    owner: root
    group: root
    mode: 0444
    state: file
  when: res.stat.exists == True
  tags:
   - scored
   - section3.13
   - section3.14

- stat: path=/var/run/docker.sock
  register: res

- name: |
        "3.15 Ensure that Docker socket file ownership is set to root:docker (Scored)"
        "3.16 Ensure that Docker socket file permissions are set to 660 or more restrictive (Scored)"
  file:
    path: /var/run/docker.sock
    owner: root
    group: docker
    mode: 0660
    state: file
  when: res.stat.exists == True
  tags:
   - scored
   - section3.15
   - section3.16


- stat: path=/etc/docker/daemon.json
  register: res

- name: |
        "3.17 Ensure that daemon.json file ownership is set to root:root (Scored)"
        "3.18 Ensure that daemon.json file permissions are set to 644 or more restrictive (Scored)"
  file:
    path: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644
    state: file
  when: res.stat.exists == True
  tags:
   - scored
   - section3.17
   - section3.18


- stat: path=/etc/default/docker
  register: res

- name: |
        "3.19 Ensure that /etc/default/docker file ownership is set to root:root (Scored)"
        "3.20 Ensure that /etc/default/docker file permissions are set to 644 or more restrictive (Scored)"
  file:
    path: /etc/default/docker
    owner: root
    group: root
    mode: 0644
    state: file
  when: res.stat.exists == True
  tags:
   - scored
   - section3.19
   - section3.20


