---
- name: Control Plane Components
  include: control_1.yml
  when: control_1 | bool and inventory_hostname in groups['kubernetes_masters']

- name: etcd
  include: control_2.yml
  when: control_2 | bool and inventory_hostname in groups['kubernetes_masters']

- name: Control Plane Configuration
  include: control_3.yml
  when: control_3 | bool and inventory_hostname in groups['kubernetes_masters']

- name: Generate Certs
  include: generate_cert.yml
  when: generate_cert | bool and inventory_hostname in groups['kubernetes_master']

- name: Copy Certs to Master
  include: copy_files.yml
  when: copy_files | bool and inventory_hostname in groups['kubernetes_master_replicas']

- name: Policies
  include: control_5.yml
  when: control_5 | bool and inventory_hostname in groups['kubernetes_masters']